# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-16 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0003_auto_20190116_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaires.Choice', verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='dialog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dialogs.Dialog', verbose_name='Dialog'),
        ),
    ]
