# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-15 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150, verbose_name='Choice text')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Question text')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Dialog Finished')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireFinishText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150, verbose_name='Choice text')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.Questionnaire', verbose_name='Questionnaire'),
        ),
        migrations.AddField(
            model_name='choice',
            name='finish',
            field=models.ForeignKey(default=None, help_text='If specified - a dialog will be finished on this choice', null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaires.QuestionnaireFinishText', verbose_name='Is finish'),
        ),
        migrations.AddField(
            model_name='choice',
            name='next_question',
            field=models.ForeignKey(default=None, help_text='Link to next question. If exist.', null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaires.Question', verbose_name='Next question'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(help_text='Question the choice belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='questionnaires.Question', verbose_name='Question'),
        ),
    ]
