# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-16 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_remove_questionnaire_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='finish',
            field=models.ForeignKey(blank=True, help_text='If specified - a dialog will be finished on this choice', null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaires.QuestionnaireFinishText', verbose_name='Is finish'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='next_question',
            field=models.ForeignKey(blank=True, help_text='Link to next question. If exist.', null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaires.Question', verbose_name='Next question'),
        ),
    ]
